### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by audreytoskin** [flathub/org.kde.krename#36]
I just installed KRename 5.0.2 from Flathub on Fedora 39 (x86_64, AMD APU), and KRename is missing couple of the 'plugins' that are usually included with other builds:

- PoDoFo (PDF) Plugin
- Exiv2 (JPEG/TIFF Exif) Plugin

I don't see any way to add plugins to an already-compiled build of KRename. Let me know if you need any other info, and thanks :)

![Screenshot from 2024-04-14 23-07-02](https://github.com/flathub/org.kde.krename/assets/3881885/bf34e3d9-d01d-4e46-890e-7dbbc4d04e3d)

**Comment by travier** [comment]
Thanks for the report. Unfortunately, krename fails to build for both plugins:
- https://github.com/flathub/org.kde.krename/pull/37
- https://github.com/flathub/org.kde.krename/pull/38

**Comment by travier** [comment]
Nevermind, the PoDoFo build succeeded.

**Comment by travier** [comment]
Looks like an older version of exiv2 worked.
